---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php (Ubuntu) 
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php (CentOS) 
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
